# Generated by Django 4.1 on 2022-10-20 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treecartservices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('c_password', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
    ]
